// Why: pi has no settings.json hook surface — its extensibility is the
// in-process TypeScript extension API (pi.on('agent_start'), 'tool_call',
// etc.). To get pi panes into the unified agent-hooks pipeline alongside
// Claude/Codex/Gemini/OpenCode/Cursor, we ship a bundled extension into
// the selected Pi/OMP extension dir (PiTitlebarExtensionService) that POSTs to
// /hook/<kind> using the same ORCA_AGENT_HOOK_* + ORCA_PANE_KEY env that every
// PTY already receives from ipc/pty.ts.
//
// Each Pi process gets its own paneKey through env. Like the OpenCode plugin,
// the returned source is a string (loaded by jiti from disk inside the pi process), so we
// keep the source body in plain JS without TS types and avoid pulling pi or
// any Orca dep into the pi runtime.
import type { PiAgentKind } from '../../shared/pi-agent-kind'

export const ORCA_PI_AGENT_STATUS_EXTENSION_FILE = 'orca-agent-status.ts'

export function getPiAgentStatusExtensionSource(kind: PiAgentKind = 'pi'): string {
  // Why: keep this string self-contained — it runs inside the pi process,
  // so it cannot import from Orca's main bundle. fs/http coords come from
  // the same endpoint file the OpenCode plugin reads (process.env is frozen
  // at PTY spawn, so on Orca restart we have to re-read it from disk).
  return [
    '// Why: no package-specific type import here. Pi and OMP expose the same',
    '// extension API, but publish their types under different package names.',
    '// Why: warn-once so a recurring parse error on a malformed endpoint',
    '// file does not spam stderr inside the pi TUI on every event.',
    'let warnedBadEndpoint = false',
    '',
    '// Why: re-reading the endpoint file on every event is cheap (small file,',
    '// rare changes) but stat+mtime caching avoids re-parsing on every event',
    '// during streaming tool execution. Mirrors the OpenCode plugin cache shape.',
    "let cachedEndpointKey = ''",
    'let cachedEndpointValues: Record<string, string> | null = null',
    '',
    'function readEndpointFile(): Record<string, string> | null {',
    '  const path = process.env.ORCA_AGENT_HOOK_ENDPOINT',
    '  if (!path) return null',
    '  try {',
    "    const fs = require('fs')",
    '    try {',
    '      const stat = fs.statSync(path)',
    "      const cacheKey = stat.mtimeMs + ':' + stat.size + ':' + stat.ino",
    '      if (cacheKey === cachedEndpointKey && cachedEndpointValues) {',
    '        return cachedEndpointValues',
    '      }',
    "      const contents: string = fs.readFileSync(path, 'utf8')",
    '      const out: Record<string, string> = {}',
    '      for (const line of contents.split(/\\r?\\n/)) {',
    '        // Why: parse `KEY=VALUE` (POSIX endpoint.env) and `set KEY=VALUE`',
    '        // (Windows endpoint.cmd) with one regex; strip a trailing CR so',
    '        // mixed-EOL files do not leak \\r into the value.',
    '        const m = line.match(/^(?:set\\s+)?([A-Z0-9_]+)=(.*)$/)',
    "        if (m) out[m[1]] = m[2].replace(/\\r$/, '')",
    '      }',
    '      cachedEndpointKey = cacheKey',
    '      cachedEndpointValues = out',
    '      return out',
    '    } catch (ioErr) {',
    "      cachedEndpointKey = ''",
    '      cachedEndpointValues = null',
    '      throw ioErr',
    '    }',
    '  } catch (err: unknown) {',
    '    const code = (err as { code?: string } | null)?.code',
    "    if (err && code !== 'ENOENT' && !warnedBadEndpoint) {",
    '      warnedBadEndpoint = true',
    "      console.warn('[orca-pi-status] failed to parse endpoint file:', (err as Error).message)",
    '    }',
    '    return null',
    '  }',
    '}',
    '',
    'function resolveHookCoords() {',
    '  const fileEnv = readEndpointFile() || {}',
    '  return {',
    '    port: fileEnv.ORCA_AGENT_HOOK_PORT || process.env.ORCA_AGENT_HOOK_PORT,',
    '    token: fileEnv.ORCA_AGENT_HOOK_TOKEN || process.env.ORCA_AGENT_HOOK_TOKEN,',
    "    env: fileEnv.ORCA_AGENT_HOOK_ENV || process.env.ORCA_AGENT_HOOK_ENV || '',",
    "    version: fileEnv.ORCA_AGENT_HOOK_VERSION || process.env.ORCA_AGENT_HOOK_VERSION || '',",
    '  }',
    '}',
    '',
    'function processName(value: unknown): string {',
    "  return String(value || '').split(/[\\\\/]/).pop()?.toLowerCase() || ''",
    '}',
    '',
    'function resolveHookPath(): string {',
    `  const configuredPath = '/hook/${kind}'`,
    '  const executableNames = [',
    '    processName(process.title),',
    '    processName(process.env._),',
    '    processName(process.argv[1]),',
    '    processName(process.argv[0])',
    '  ]',
    '  const isOmpExecutable = executableNames.some((name) =>',
    "    ['omp', 'omp.js', 'omp.sh', 'omp.cmd', 'omp.exe', 'omp.bat'].includes(name)",
    '  )',
    '  // Why: a bare shell may launch either Pi or OMP after spawn. Runtime',
    '  // executable detection keeps that status labeled',
    '  // as OMP instead of silently reporting it as Pi.',
    '  if (isOmpExecutable) {',
    "    return '/hook/omp'",
    '  }',
    '  return configuredPath',
    '}',
    '',
    'async function post(hookEventName: string, extra: Record<string, unknown> = {}): Promise<void> {',
    '  const coords = resolveHookCoords()',
    '  const paneKey = process.env.ORCA_PANE_KEY',
    '  if (!coords.port || !coords.token || !paneKey) return',
    '  const url = `http://127.0.0.1:${coords.port}${resolveHookPath()}`',
    '  const body = JSON.stringify({',
    '    paneKey,',
    "    tabId: process.env.ORCA_TAB_ID || '',",
    "    worktreeId: process.env.ORCA_WORKTREE_ID || '',",
    '    env: coords.env,',
    '    version: coords.version,',
    '    payload: { hook_event_name: hookEventName, ...extra },',
    '  })',
    '  try {',
    '    await fetch(url, {',
    "      method: 'POST',",
    '      headers: {',
    "        'Content-Type': 'application/json',",
    "        'X-Orca-Agent-Hook-Token': coords.token,",
    '      },',
    '      body,',
    '    })',
    '  } catch {',
    '    // Why: status reporting must never fail the pi run just because Orca',
    '    // is unavailable or the loopback request failed (e.g. Orca restart).',
    '  }',
    '}',
    '',
    '// Why: pi assistant messages carry content as an array of parts',
    "// ({ type: 'text', text } / tool_use / tool_result / reasoning). We only",
    "// surface the concatenated text parts as the visible 'last assistant",
    "// message' for the dashboard preview — tool_use / reasoning would be",
    '// noise (the dashboard already shows the active tool name + input).',
    'function extractAssistantText(message: unknown): string {',
    "  if (!message || typeof message !== 'object') return ''",
    '  const content = (message as { content?: unknown }).content',
    "  if (typeof content === 'string') return content",
    "  if (!Array.isArray(content)) return ''",
    "  let out = ''",
    '  for (const part of content) {',
    "    if (part && typeof part === 'object' && (part as { type?: unknown }).type === 'text') {",
    '      const text = (part as { text?: unknown }).text',
    "      if (typeof text === 'string') out += text",
    '    }',
    '  }',
    '  return out',
    '}',
    '',
    "// Why: pi's tool_call event input shape is tool-specific (event.input is",
    '// the raw args object). The agent-hooks server already runs',
    '// deriveToolInputPreview(toolName, input) to render a friendly preview',
    "// for known tool names ('bash' → command, 'read'/'write'/'edit' → path,",
    '// etc.), so we forward the raw object verbatim under the same field',
    '// names Claude uses (tool_name / tool_input) and let the server pick the',
    '// preview. Keeps tool-name knowledge centralized on the receiver side.',
    'export default function (pi): void {',
    "  pi.on('before_agent_start', async (event) => {",
    "    await post('before_agent_start', { prompt: event.prompt ?? '' })",
    '  })',
    '',
    "  pi.on('agent_start', async () => {",
    "    await post('agent_start')",
    '  })',
    '',
    "  pi.on('tool_execution_start', async (event) => {",
    "    await post('tool_execution_start', {",
    '      tool_name: event.toolName,',
    '      tool_input: event.args,',
    '    })',
    '  })',
    '',
    "  pi.on('tool_call', async (event) => {",
    "    await post('tool_call', {",
    '      tool_name: event.toolName,',
    '      tool_input: event.input,',
    '    })',
    '  })',
    '',
    "  pi.on('tool_execution_end', async (event) => {",
    "    await post('tool_execution_end', {",
    '      tool_name: event.toolName,',
    '    })',
    '  })',
    '',
    "  // Why: capture the assistant's final text on each completed message",
    '  // so the dashboard preview reflects the most recent reply even before',
    '  // agent_end fires. message_end is the right hook because pi guarantees',
    '  // it fires after the message is finalized (post-streaming).',
    "  pi.on('message_end', async (event) => {",
    "    if (event.message?.role !== 'assistant') return",
    '    const text = extractAssistantText(event.message)',
    '    if (!text) return',
    "    await post('message_end', { role: 'assistant', text })",
    '  })',
    '',
    "  pi.on('agent_end', async () => {",
    "    await post('agent_end')",
    '  })',
    '',
    "  pi.on('session_shutdown', async () => {",
    "    await post('session_shutdown')",
    '  })',
    '}',
    ''
  ].join('\n')
}
