export {
  buildAgentFeatureSkillInstallCommand,
  COMPUTER_USE_SKILL_INSTALL_COMMAND,
  COMPUTER_USE_SKILL_NAME,
  ORCA_CLI_SKILL_INSTALL_COMMAND,
  ORCA_CLI_ORCHESTRATION_SKILL_INSTALL_COMMAND,
  ORCA_CLI_SKILL_NAME,
  ORCHESTRATION_SKILL_NAME
} from '../../../shared/agent-feature-install-commands'
