import type {
  SetupSplitDirection,
  TuiAgent,
  Worktree,
  WorktreeSetupLaunch
} from '../../../shared/types'
import type { EventProps } from '../../../shared/telemetry-events'
import { shouldAutoCreateInitialTerminal } from '@/components/terminal/initial-terminal'
import { buildSetupRunnerCommand } from './setup-runner'
import { buildAgentStartupPlan } from './tui-agent-startup'
import { CLIENT_PLATFORM } from './new-workspace'
import { tuiAgentToAgentKind } from './telemetry'
import { agentKindToTuiAgent } from '../../../shared/agent-kind'
import { useAppStore } from '@/store'
import type { PendingSidebarWorktreeReveal } from '@/store/slices/ui'
import {
  activateWebRuntimeSessionWorktree,
  isWebRuntimeSessionActive
} from '@/runtime/web-runtime-session'
import {
  setWorktreeNavActivator,
  setWorktreeNavViewActivator
} from '@/store/slices/worktree-nav-history'
import { isTuiAgent } from '../../../shared/tui-agent-config'

/** Telemetry payload threaded from the launch site to `pty:spawn`. Main
 *  fires `agent_started` only after the spawn succeeds — see
 *  telemetry-plan.md§Agent launch semantics. */
export type AgentStartedTelemetry = EventProps<'agent_started'>

// Why: issue commands can originate from two sources with different shapes —
// (1) a repo-level runner script generated by main (WorktreeSetupLaunch), or
// (2) a user-typed command template substituted in the TaskPage flow.
// We accept either so callers don't need to synthesize a runner script file
// just to queue a direct command string.
export type IssueCommandLaunch =
  | WorktreeSetupLaunch
  | { command: string; env?: Record<string, string> }

type WorktreeActivationStore = {
  tabsByWorktree: Record<string, { id: string }[]>
  createTab: (
    worktreeId: string,
    targetGroupId?: string,
    shellOverride?: string,
    options?: {
      pendingActivationSpawn?: boolean
      launchAgent?: TuiAgent
      recordInteraction?: boolean
    }
  ) => { id: string }
  setActiveTab: (tabId: string) => void
  setTabCustomTitle: (
    tabId: string,
    title: string | null,
    opts?: { recordInteraction?: boolean }
  ) => void
  reconcileWorktreeTabModel: (worktreeId: string) => { renderableTabCount: number }
  queueTabStartupCommand: (
    tabId: string,
    startup: {
      command: string
      env?: Record<string, string>
      initialAgentStatus?: { agent: TuiAgent; prompt: string }
      telemetry?: AgentStartedTelemetry
    }
  ) => void
  queueTabSetupSplit: (
    tabId: string,
    startup: { command: string; env?: Record<string, string>; direction: SetupSplitDirection }
  ) => void
  queueTabIssueCommandSplit: (
    tabId: string,
    startup: { command: string; env?: Record<string, string> }
  ) => void
}

/**
 * Shared activation sequence used by the worktree palette, AddRepoDialog,
 * and AddWorktreeDialog. Covers: cross-repo `activeRepoId` switch,
 * `activeView` back to terminal, `setActiveWorktree`, initial terminal
 * creation, sidebar filter clearing, and sidebar reveal.
 *
 * The caller only passes `worktreeId`; the helper derives `repoId`
 * internally via `findWorktreeById`. Returns early without side effects
 * if the worktree is not found (e.g. deleted between palette open and select).
 */
export type ActivateAndRevealResult = {
  /** Id of the primary terminal tab seeded with `opts.startup`, when one was
   *  created during this activation call. Callers that want to target the
   *  exact pane the startup command ran in (e.g. to await agent readiness
   *  and paste follow-up text) should use this rather than peeking at
   *  `activeTabIdByWorktree`, which may point at another tab if setup or
   *  issue-command scripts opened their own. */
  primaryTabId: string | null
}

function buildCreatedAgentReopenStartup(worktree: Worktree):
  | {
      command: string
      env?: Record<string, string>
      telemetry: AgentStartedTelemetry
    }
  | undefined {
  const agent = worktree.createdWithAgent
  if (!isTuiAgent(agent)) {
    return undefined
  }

  const startupPlan = buildAgentStartupPlan({
    agent,
    prompt: '',
    cmdOverrides: useAppStore.getState().settings?.agentCmdOverrides ?? {},
    platform: CLIENT_PLATFORM,
    allowEmptyPromptLaunch: true
  })
  if (!startupPlan) {
    return undefined
  }

  return {
    command: startupPlan.launchCommand,
    ...(startupPlan.env ? { env: startupPlan.env } : {}),
    telemetry: {
      agent_kind: tuiAgentToAgentKind(agent),
      launch_source: 'sidebar',
      request_kind: 'resume'
    }
  }
}

export function activateAndRevealWorktree(
  worktreeId: string,
  opts?: {
    startup?: {
      command: string
      env?: Record<string, string>
      initialAgentStatus?: { agent: TuiAgent; prompt: string }
      telemetry?: AgentStartedTelemetry
    }
    setup?: WorktreeSetupLaunch
    issueCommand?: IssueCommandLaunch
    sidebarRevealBehavior?: PendingSidebarWorktreeReveal['behavior']
  }
): ActivateAndRevealResult | false {
  const state = useAppStore.getState()
  const wt = state.getKnownWorktreeById(worktreeId)
  if (!wt) {
    return false
  }

  // 1. Set activeRepoId if crossing repos
  if (wt.repoId !== state.activeRepoId) {
    state.setActiveRepo(wt.repoId)
  }

  // 2. Switch any non-terminal view back to terminal
  if (state.activeView !== 'terminal') {
    state.setActiveView('terminal')
  }

  // 3. Core activation: sets activeWorktreeId, restores per-worktree state,
  // clears unread, bumps dead PTY generations, triggers GitHub refresh
  state.setActiveWorktree(worktreeId)
  if (isWebRuntimeSessionActive(useAppStore.getState().settings?.activeRuntimeEnvironmentId)) {
    // Why: paired web clients own only local selection state. The desktop host
    // must also activate the worktree so hidden renderer-owned terminal panes
    // mount and publish session surfaces back to the web client.
    void activateWebRuntimeSessionWorktree({ worktreeId })
  }

  // Why: record focus recency for Cmd+J's empty-query ordering BEFORE any
  // later async step (initial terminal / reveal) could throw — the user
  // already perceives the switch as successful the instant activeWorktreeId
  // flips, so the recency stamp must land with the same guarantee. Separate
  // from recordWorktreeVisit (nav-history) and from worktree.lastActivityAt
  // (background signal) on purpose — see docs/cmd-j-empty-query-ordering.md.
  state.markWorktreeVisited(worktreeId)

  // Why: activateAndRevealWorktree always ends in 'terminal' view (step 2),
  // and Settings/Tasks transitions do not pass through this function, so no
  // view-guard is needed here. The guard skips re-recording when the caller
  // is goBackWorktree/goForwardWorktree, which mutate the history index
  // directly instead of treating the target as a new visit.
  if (!state.isNavigatingHistory) {
    state.recordWorktreeVisit(worktreeId)
  }

  // 4. Ensure a focusable surface exists for externally-created worktrees
  const primaryTabId = ensureWorktreeHasInitialTerminal(
    useAppStore.getState(),
    worktreeId,
    opts?.startup ?? buildCreatedAgentReopenStartup(wt),
    opts?.setup,
    opts?.issueCommand
  )

  // 5. Clear sidebar filters that would hide the target worktree
  // Why: revealWorktreeInSidebar relies on the worktree card being rendered
  // in the sidebar. If sidebar filters exclude the target, the card is never
  // rendered and the reveal silently no-ops.
  if (state.filterRepoIds.length > 0 && !state.filterRepoIds.includes(wt.repoId)) {
    state.setFilterRepoIds([])
  }

  // 6. Reveal in sidebar
  if (opts?.sidebarRevealBehavior) {
    state.revealWorktreeInSidebar(worktreeId, { behavior: opts.sidebarRevealBehavior })
  } else {
    state.revealWorktreeInSidebar(worktreeId)
  }

  return { primaryTabId }
}

export function ensureWorktreeHasInitialTerminal(
  store: WorktreeActivationStore,
  worktreeId: string,
  startup?: {
    command: string
    env?: Record<string, string>
    initialAgentStatus?: { agent: TuiAgent; prompt: string }
    telemetry?: AgentStartedTelemetry
  },
  setup?: WorktreeSetupLaunch,
  issueCommand?: IssueCommandLaunch
): string | null {
  const { renderableTabCount } = store.reconcileWorktreeTabModel(worktreeId)
  // Why: activation can now restore editor- or browser-only worktrees from the
  // reconciled tab-group model. Creating a terminal just because the legacy
  // terminal slice is empty would reopen worktrees with an unexpected extra tab.
  if (!shouldAutoCreateInitialTerminal(renderableTabCount)) {
    return null
  }
  // Why: remote web clients mirror the runtime server's session tabs. A local
  // activation fallback can spawn a second host terminal before the mirror lands.
  if (
    isWebRuntimeSessionActive(useAppStore.getState().settings?.activeRuntimeEnvironmentId ?? null)
  ) {
    return null
  }

  // Why: this tab only exists because the user clicked/activated a worktree
  // that had no focusable surface yet. Tag it so the resulting PTY spawn
  // does not count as activity and reshuffle the Recent sort. Explicit
  // "New Tab" actions (handleNewTab in Terminal.tsx) do not set the flag.
  //
  // Why: the initial terminal can be seeded with a coding agent (new-workspace
  // flow, or reopening an empty worktree created with an agent). The startup
  // payload only carries telemetry's agent_kind, so reverse it back to a
  // TuiAgent to stamp the tab — giving it the provider icon before any hook.
  const launchAgent = startup?.telemetry
    ? (agentKindToTuiAgent(startup.telemetry.agent_kind) ?? undefined)
    : undefined
  const terminalTab = store.createTab(worktreeId, undefined, undefined, {
    pendingActivationSpawn: true,
    ...(launchAgent ? { launchAgent } : {})
  })
  store.setActiveTab(terminalTab.id)

  // Why: the new-workspace flow can seed the first terminal with a selected
  // coding agent and user prompt. Queue that startup command on the initial
  // pane so the main terminal begins in the requested agent session instead of
  // opening to an idle shell and forcing the user to repeat the same prompt.
  if (startup) {
    store.queueTabStartupCommand(terminalTab.id, startup)
  }

  // Why: the setup script launch location is user-configurable. The default
  // 'new-tab' creates a separate background tab titled "Setup" without
  // stealing focus from the main terminal, so setup output never crowds the
  // primary pane; 'split-vertical' and 'split-horizontal' keep the setup
  // output adjacent to the main terminal via a split.
  if (setup) {
    const mode = useAppStore.getState().settings?.setupScriptLaunchMode ?? 'new-tab'
    const setupCommand = {
      command: buildSetupRunnerCommand(setup.runnerScriptPath),
      env: setup.envVars
    }
    if (mode === 'new-tab') {
      const setupTab = store.createTab(worktreeId, undefined, undefined, {
        recordInteraction: false
      })
      // Why: createTab auto-activates the new tab. Revert activation so the
      // user's focus stays on the primary terminal — per the design, the
      // Setup tab runs unattended in the background.
      store.setActiveTab(terminalTab.id)
      // Why: customTitle wins over the auto-generated "Terminal N" label
      // everywhere the tab is rendered (tab bar, switcher, session snapshots),
      // so labeling via customTitle is the single authoritative source.
      store.setTabCustomTitle(setupTab.id, 'Setup', { recordInteraction: false })
      store.queueTabStartupCommand(setupTab.id, setupCommand)
    } else {
      store.queueTabSetupSplit(terminalTab.id, {
        ...setupCommand,
        direction: mode === 'split-horizontal' ? 'horizontal' : 'vertical'
      })
    }
  }

  // Why: when the user links a GitHub issue and opts into that repo's
  // per-user issue automation, spawn a separate split pane to run the
  // agent command. Queued independently from setup so both can start in
  // parallel; repo bootstrap and personal issue workflows are separate
  // concerns, so Orca should not invent a dependency between them.
  if (issueCommand) {
    // Why: WorktreeSetupLaunch carries a runner-script file (from main) and we
    // shell out to bash; the TaskPage variant is already an expanded command
    // string, so pass it through directly.
    const queuedIssueCommand =
      'runnerScriptPath' in issueCommand
        ? {
            command: buildSetupRunnerCommand(issueCommand.runnerScriptPath),
            env: issueCommand.envVars
          }
        : { command: issueCommand.command, env: issueCommand.env }
    store.queueTabIssueCommandSplit(terminalTab.id, queuedIssueCommand)
  }

  return terminalTab.id
}

// Why: break the import cycle — the nav-history slice must call
// activateAndRevealWorktree from goBack/goForward, but the slice lives under
// @/store, which activation already imports from. Registering the activator
// at module init here lets the slice call back without importing this file.
setWorktreeNavActivator(activateAndRevealWorktree)

// Why: page entries in nav history replay through setActiveView(...)
// (not open*Page) so back/forward does not mutate previousViewBefore* or
// append duplicate history. See navigateToIndex for the replay branch.
setWorktreeNavViewActivator((entry) => {
  if (entry === 'automations') {
    useAppStore.getState().setActiveView(entry)
    return
  }
  if (entry === 'tasks') {
    useAppStore.setState((state) => ({
      activeView: 'tasks',
      githubTaskDrawerWorkItem: null,
      taskPageData: {
        ...state.taskPageData,
        openGitHubWorkItem: undefined,
        openGitHubInitialTab: undefined,
        openLinearIssue: undefined
      }
    }))
    return
  }
  if (entry.source === 'github') {
    useAppStore.setState((state) => ({
      activeView: 'tasks',
      taskPageData: {
        ...state.taskPageData,
        taskSource: 'github',
        preselectedRepoId: entry.workItem.repoId,
        openGitHubWorkItem: entry.workItem,
        openGitHubInitialTab: entry.initialTab,
        openLinearIssue: undefined
      }
    }))
    return
  }
  useAppStore.setState((state) => ({
    activeView: 'tasks',
    githubTaskDrawerWorkItem: null,
    taskPageData: {
      ...state.taskPageData,
      taskSource: 'linear',
      openGitHubWorkItem: undefined,
      openGitHubInitialTab: undefined,
      openLinearIssue: entry.issue
    }
  }))
})
